Add phpday elephpant
jgrossi/elephpant.me pull request #54
Opened 2020-09-21 13:55 UTC by IgorSantos17

2020-09-21 15:06 UTC, jgrossi requested changes

2020-09-21 15:06 UTC, jgrossi commented on resources/data/elephpants.json
> +            "image": "https://i.imgur.com/26fk9QV.jpg"
the image is wrong

2020-09-22 13:34 UTC, IgorSantos17 commented on resources/data/elephpants.json
> +            "image": "https://i.imgur.com/26fk9QV.jpg"
sorry man, adjusted!

2020-09-22 16:54 UTC, jgrossi approved these changes

2020-09-22 16:54 UTC, merged