Profile Card #61
jgrossi/elephpant.me pull request #64
Opened 2020-10-16 20:19 UTC by g1dra

Added requested changes. Have some extra logic if user register with only name to generate initials. 
Full name is not required at the moment.

2020-10-17 14:33 UTC, jgrossi requested changes
check the tugboat preview please. not sure if the result is what you imagined

2020-10-17 17:13 UTC, g1dra commented on app/Http/Controllers/HerdController.php
> +
Should be ok now.

2020-10-19 20:00 UTC, IgorSantos17 commented
Hey,
as I said, there is already an open PR #13,
it even has a good implementation, maybe it would not be better to continue it?

2020-10-19 20:50 UTC, g1dra commented
Sure

2020-10-19 20:56 UTC, closed without merging